### ISSUE TITLE
Issue with Elm-live

### ISSUE THREAD

**Issue by karismatic-megafauna** [rtfeldman/elm-workshop#14]
```sh
~/Code/elm-workshop/part1
master ❯❯ elm-live Main.elm --open --pushstate --output=elm.js
zsh: command not found: elm-live
```

Seems like https://github.com/tomekwi/elm-live isn't in the elm-package.json, should it be?

Thanks!

**Comment by rtfeldman** [comment]
`elm-live` comes from `npm` - check out Step 4 of [Getting Started](https://github.com/rtfeldman/elm-workshop#getting-started) 🙂

**Comment by karismatic-megafauna** [comment]
Ah! Thank you :)
