### ISSUE TITLE
Dependencies are not up to date

### ISSUE THREAD

**Issue by okbel** [rtfeldman/elm-workshop#7]
<img width="588" alt="screen shot 2016-12-07 at 5 02 14 pm" src="https://cloud.githubusercontent.com/assets/1401559/20984487/3770ef6a-bc9f-11e6-8d72-7287dc428d0e.png">

This PR https://github.com/rtfeldman/elm-workshop/pull/6 address this issue.

Thanks!

**Comment by rtfeldman** [comment]
`master` is now on 0.18, and all the `elm-package.json` files should be up to date now!

**Comment by katbow** [comment]
@rtfeldman it looks like the [`elm-package.json`](https://github.com/rtfeldman/elm-workshop/blob/master/part9/tests/elm-package.json) in the `tests` folder for [part9](https://github.com/rtfeldman/elm-workshop/tree/master/part9) was missed in the update. 

I updated the dependencies for this in PR #10 .

Cheers!
